spring.application.name=demo3


# src/main/resources/application.properties

# ??????? URL
app.recommendation-service.url=http://localhost:5000

# ????? (??)
server.port=8080

# --- ?????? ---
# ? root logger ??? INFO (?????)
# logging.level.root=INFO

# ?????????????? DEBUG?????????????
logging.level.com.example.demo=DEBUG

# ?????? Spring Web ?????????? HTTP ??/??????????
# logging.level.org.springframework.web.client=DEBUG
# logging.level.org.apache.http=DEBUG
# logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
# ---------------------